CREATE DATABASE project_3;
USE project_3;
SET SQL_SAFE_UPDATES = 0;

CREATE TABLE employee(empId INT PRIMARY KEY AUTO_INCREMENT,
EMP_NAME VARCHAR(100),
SUR_NAME VARCHAR(100),
Address TEXT
);

SELECT * FROM employee;